#!/packages/run/links/bin/perl -I/home/xtoth1/kontrPublic


use StudentInfo;
use Try::Tiny;
use utf8;
use Moose::Util::TypeConstraints;
use Types;
use FISubmission;
use FIHomework;
no utf8;

# required parameters: class homework type
if (scalar @ARGV != 3)
{
	printf	"Tento skript vyžaduje přesně tři parametry.\n".
		"\t* předmět (pb071 pro cecko, pb161 pro cpp)\n".
		"\t* domácí úkol (hwXX)\n".
		"\t* typ odevzdání (nanecisto, naostro)\n";

	exit 1;
}

chdir "/home/xtoth1/kontrPublic";

my $class = $ARGV[0];
my $homework = $ARGV[1];
my $type = $ARGV[2];

# validate parameters
if (not find_type_constraint('SubmissionClass')->check($class))
{
	printf	"Podporované hodnoty pro předmět jsou:\n".
		"\t* pb071 - Uvod do jazyka C\n".
		"\t* pb161 - Programovani v jazyce C++\n";

	exit 1;
}

if (not find_type_constraint('SubmissionMode')->check($type))
{
	printf	"Podporované hodnoty pro typ odevzdání:\n".
		"\t* nanecisto\n".
		"\t* naostro\n";

	exit 1;
}

my $info;
my $login;
try {
	$login = getlogin || getpwuid($<) || "Anonymous";
	$info = new StudentInfo(login => $login, class => $class);
} catch {
	printf  "Nejste zadaven v systému automatických oprav, nebo je v databázi chyba.\n".
		"Kontaktujte prosím správce (toth\@fi.muni.cz) a přiložte následující text:\n\n\n";
	printf $_;
} finally {
	my $h = new FIHomework(name => $homework, class => $class);
	my $s = new FISubmission(user => $info, homework => $h, mode => $type);
	if ($info->is_special())
	{
		printf "Detekován speciální uživatel. Test otevřeného úkolu a zpoždění při opravě přeskočeno.\n\n"; 
	}
	elsif (not $h->is_opened($type))
	{
		printf "Odevzdávání domácího úkolu \"$homework\" v režimu \"$type\" zatím není otevřeno studentům.\n";
		exit 1; 
	}
	if (not $s->is_submitted) {
		printf "Tento domácí úkol nemáte v tomto režimu odevzdán.\n";
		exit 1;
	}

	printf "Probíhá zrušení odevzdání domácího úkolu \"$homework\" v režimu \"$type\".\n\n";
	printf "Student detekován jako: '".$info->name."' UČO: '".$info->uco."' email: '".$info->email."' unix login: '".$info->login."'\n";
	printf "Student patří pod: '".$info->teacher->name."' UČO: '".$info->teacher->uco."' email: '".$info->teacher->email."' unix login: '".$info->teacher->login."'\n"  unless $info->is_special;
	printf "Pokud je některý z údajů nesprávný, okamžitě kontaktujte správce kontru.\n\n";

	if (not $s->remove()) {
		printf "Zrušení odevzdání domácího úkolu se nezdařilo, zkuste to prosím znovu a pokud uvidíte znovu stejnou chybu, tak kontaktujte prosím správce (toth\@fi.muni.cz) a přiložte následující text:\n\n\n";
		printf $_;
	}
}
